import express from "express";
import authRoutes from "./authRoutes.js";
import userRoutes from "./userRoutes.js";
import profileRoutes from "./profileRoutes.js";
import harvestRoutes from "./harvestRoutes.js";
import productRoutes from "./productRoutes.js";
import inventoryRoutes from "./inventoryRoutes.js";
import marketplaceRoutes from "./marketplaceRoutes.js";
import cartRoutes from "./cartRoutes.js";
import orderRoutes from "./orderRoutes.js";
import paymentRoutes from "./paymentRoutes.js";
import escrowRoutes from "./escrowRoutes.js";
import walletRoutes from "./walletRoutes.js";
import shipmentRoutes from "./shipmentRoutes.js";
import invoiceRoutes from "./invoiceRoutes.js";
import blockchainRoutes from "./blockchainRoutes.js";
import blockchainLogRoutes from "./blockchainLogRoutes.js";
import traceRoutes from "./traceRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import messageRoutes from "./messageRoutes.js";
import reviewRoutes from "./reviewRoutes.js";
import adminRoutes from "./adminRoutes.js";

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/profiles", profileRoutes);
router.use("/harvests", harvestRoutes);
router.use("/products", productRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/marketplace", marketplaceRoutes);
router.use("/cart", cartRoutes);
router.use("/orders", orderRoutes);
router.use("/payments", paymentRoutes);
router.use("/escrow", escrowRoutes);
router.use("/wallet", walletRoutes);
router.use("/shipments", shipmentRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/blockchain", blockchainRoutes);
router.use("/blockchain-logs", blockchainLogRoutes);
router.use("/trace", traceRoutes);
router.use("/notifications", notificationRoutes);
router.use("/messages", messageRoutes);
router.use("/reviews", reviewRoutes);
router.use("/admin", adminRoutes);

export default router;
